---
title: "Spectro_Photo_Validation"
author: "Chloe Fouilloux"
date: '2022-10-18'
output: html_document
---

Here I show the parameterization of models used for spectrophotometry and photo colour analysis to show model validation. Here we will only consider the *O. pumilio* data because we have spectrophotometer and photography measurements for nursery water samples. 

```{r Libraries}
library(tidyverse)
library(glmmTMB)
library(DHARMa)
```


Now, let's load some data

```{r Data Wrangling}
#las<- read_csv("LAS_VISION.csv") #without spectral data
las<- read_csv("LAS_VISION_AUG2022.csv") #spectral data from AUG. 22 2022 code-a-thon

las <- las %>%
       mutate(Trial = as.factor(Trial),
              Tad_ID = as.factor(Tad_ID),
              Condition = as.factor(Condition),
              Predator = as.factor(Predator)) 
#activity
activity <- las %>%
           filter (Condition != "Background") %>%
           dplyr::select(! c("White", "Black")) %>%
           mutate(mass_diff_cons = Mass - Cons_g)

activity$Predator<- forcats::fct_relevel(activity$Predator, 
                    c("Control", "Spider", "Conspecific"))

#Lets also look for black and white background trial
#background choice data
bw_choice_las <- las %>%
            filter (Condition == "Background") %>%
            mutate(p_black = Black/60, 
                   p_swim = Swim/60) 

```


Cool, now let's run our models! <3


```{r Time spent on Black background}

############################
  ##### MEAN WAVE #####
############################

m1<- glm.nb(Black ~ Mass + (Mean_Wave), 
             data = bw_choice_las) 


############################
  ##### %R channel reflectance #####
############################

mOG1<- glm.nb(Black ~ Mass + log(rMean_OG), 
             data = bw_choice_las) 

```


```{r Zone 1 Useage}

############################
  ##### MEAN WAVE #####
############################

m2<- glmmTMB(Zone_1 ~ Condition + Mean_Wave  + Predator + 
                Mass+
               (1|Tad_ID),data = activity, family = nbinom1) 

summary(m2)
simulationOutput <- simulateResiduals(fittedModel = m2)
plot(simulationOutput)
testDispersion(m2)
testZeroInflation(m2)

############################
  ##### r MEAN OG #####
############################ 

m2_rMean<- glmmTMB(Zone_1 ~  Condition + log(rMean_OG)  + Predator +
                Mass+
                #log(Mass)+
               (1|Tad_ID),data = activity, family = nbinom1) 

summary(m2_rMean)
simulationOutput <- simulateResiduals(fittedModel = m2_rMean)
plot(simulationOutput)
testDispersion(m2_rMean)
testZeroInflation(m2_rMean)


```


```{r Activity}

############################
  ##### MEAN WAVE #####
############################ 

m3<- glmmTMB(Swim ~ Condition * Mean_Wave + Predator + 
                (Mass)+
               (1|Tad_ID),data = activity, family = nbinom1) 
summary(m3)
simulationOutput <- simulateResiduals(fittedModel = m3)
plot(simulationOutput)

############################
  ##### r MEAN OG #####
############################ 

m3OG<- glmmTMB(Swim ~ 
                Condition * log(rMean_OG) + Predator +
                (Mass)+
                #offset((Mass)) +
               (1|Tad_ID), 
              data = activity, family = nbinom1) 


summary(m3OG)
simulationOutput <- simulateResiduals(fittedModel = m3OG)
plot(simulationOutput)
```











